behaviors:
  absorption:
    enabled: true
    price_impact_max: 0.0001
    time_window: 60
    volume_threshold: 1000
  exhaustion:
    confirmation_bars: 3
    enabled: true
    momentum_decay_rate: 0.7
    volume_decay_rate: 0.6
  institutional:
    consistency_threshold: 0.8
    enabled: true
    min_trades: 10
    volume_multiplier: 5.0
  stop_hunt:
    enabled: true
    reversal_time: 30
    spike_threshold: 0.002
    volume_spike: 3.0
  sweep:
    enabled: true
    levels_required: 3
    time_limit: 5
    volume_threshold: 500
